import Link from 'next/link';
import {Region,City,regions,nationalPrograms} from '@/lib/insurance-data';
import {site} from '@/lib/site';
import {getInsuranceImages} from '@/lib/insurance-images';
import InsuranceImageTopics from './InsuranceImageTopics';

export default function InsurancePage({region,city}:{region?:Region;city?:City}){
 const label=city?.name||region?.name;
 const keyword=label?`${label} 태아보험`:'태아보험';
 const imageItems=getInsuranceImages(region,city);
 const lead=city?.note||region?.summary||'임신부터 출산까지 준비해야 할 내용을 차근차근 살펴보고 우리 가족에게 필요한 보장과 지역별 출산·육아 지원정보를 함께 확인해 보세요.';
 return <main className="insurancePage">
  <section className="insuranceHero"><div className="wrap insuranceHeroGrid"><div className="insuranceHeroCopy"><span className="insuranceBadge">올바른 보험</span><h1>{label&&<em>{label}</em>} {label?'태아보험 상담':'태아보험 상담 전 알아보기'}</h1><p>{lead}</p><div className="insuranceHeroBenefits"><div><span>🛡️</span><b>보장 확인</b><small>가입 전 주요 조건 체크</small></div><div><span>📋</span><b>가입 정보</b><small>시기·기간·특약 확인</small></div><div><span>💬</span><b>상담 연결</b><small>정보 확인 후 상담 신청</small></div></div><div className="heroActions"><a className="btn btnPrimary btnLift" href={site.cpaUrl}>무료 상담 알아보기 →</a><a className="btn btnGhost" href="#지원정보">출산지원 정보 보기</a></div></div><div className="insuranceHeroVisual"><div className="heroFamilyIcon">🤰</div><div className="heroVisualText"><span>{label||'전국'} 맞춤 정보</span><strong>엄마와 아이의<br/>준비를 함께</strong><small>보험 정보 · 출산지원 · 육아정보</small></div><div className="heroMiniCard heroMiniCardA"><b>✓ 가입시기</b><span>언제 준비할까요?</span></div><div className="heroMiniCard heroMiniCardB"><b>✓ 보장내용</b><span>무엇을 확인할까요?</span></div></div></div></section>
  <div className="insuranceCrumb"><div className="wrap breadcrumbs"><Link href="/">홈</Link><span>›</span><Link href="/태아보험">태아보험</Link>{region&&<><span>›</span><Link href={`/태아보험/${region.slug}`}>{region.name} 태아보험</Link></>}{city&&<><span>›</span><b>{city.name} 태아보험</b></>}</div></div>
  <InsuranceImageTopics items={imageItems} title={`${keyword}, 어떤 정보가 필요하세요?`}/>
  <section className="section whyInsurance"><div className="wrap"><div className="whyIntro"><span className="insuranceBadge">태아보험 기초 안내</span><h2>{keyword}, 왜 미리 알아볼까요?</h2><p>태아보험은 이름만 보고 선택하기보다 출생 전후 보장 범위, 가입 가능 시기, 보장기간과 특약 조건을 함께 살펴보는 것이 중요합니다.</p></div><div className="whyCards"><article><span>🍼</span><h3>출생 전후 보장 확인</h3><p>출생 전후에 어떤 위험을 보장하는지와 보장 개시 조건을 약관에서 확인합니다.</p></article><article><span>🤱</span><h3>임신·출산 관련 확인</h3><p>산모 관련 특약이 필요한지, 보장 제외사항과 가입 조건은 무엇인지 살펴봅니다.</p></article><article><span>🌱</span><h3>아이 성장기까지 고려</h3><p>어린이보험으로 이어지는 보장기간과 갱신 여부 등 장기적인 계약조건도 함께 봅니다.</p></article></div></div></section>
  {!region&&<section className="section regionDirectory"><div className="wrap"><div className="sectionHead"><span className="insuranceBadge">지역별 태아보험</span><h2>우리 지역의 태아보험·출산정보 찾기</h2><p>전국 17개 광역지역별로 출산·육아 정책과 보험 상담 전 확인사항을 각각 정리합니다.</p></div><div className="grid">{regions.map(r=><Link className="card regionCard" key={r.slug} href={`/태아보험/${r.slug}`}><span className="pill">{r.fullName}</span><h3>{r.name} 태아보험</h3><p>{r.summary}</p><b>지역 정보 보기 →</b></Link>)}</div></div></section>}
  {region&&region.cities.length>0&&!city&&<section className="section regionDirectory"><div className="wrap"><span className="insuranceBadge">{region.fullName}</span><h2>{region.name} 주요 시 태아보험</h2><p className="muted">거주 도시를 선택하면 해당 지역의 태아보험 정보와 출산·육아 지원 내용을 확인할 수 있습니다.</p><div className="cityList">{region.cities.map(c=><Link className="cityChip" key={c.slug} href={`/태아보험/${region.slug}/${c.slug}`}>{c.name} 태아보험 <b>→</b></Link>)}</div></div></section>}
  <section className="section sectionAlt"><div className="wrap"><div className="sectionHead"><span className="insuranceBadge">상담 전 체크리스트</span><h2>{keyword} 가입 전 확인할 3가지</h2></div><div className="facts"><div className="fact"><span className="factIcon">01</span><b>가입 가능한 시기</b><p>임신 주수와 상품별 인수기준이 다를 수 있으므로 실제 가입 가능 여부와 조건을 확인합니다.</p></div><div className="fact"><span className="factIcon">02</span><b>보장기간과 특약</b><p>보장기간, 갱신 여부, 면책·감액 조건과 필요한 특약의 범위를 함께 확인합니다.</p></div><div className="fact"><span className="factIcon">03</span><b>보험료와 계약조건</b><p>보험료만 보지 않고 상품설명서와 약관, 보장 제외사항까지 함께 비교합니다.</p></div></div></div></section>
  <section className="section supportSection" id="지원정보"><div className="wrap"><div className="sectionHead"><span className="insuranceBadge">2026 공식자료 중심</span><h2>{label||'전국'} 출산·육아 지원정보</h2><p>보험과 별도로 받을 수 있는 공공지원도 함께 확인하세요. 전국 공통제도와 지자체 자체사업은 구분해서 안내합니다.</p></div><div className="supportGrid">{nationalPrograms.map(p=><article className="support" key={p.title}><div className="supportTop"><span className="pill">{p.category}</span><span className="meta">확인 {p.verifiedAt}</span></div><h3>{p.title}</h3><p>{p.summary}</p><p className="muted"><b>대상</b> {p.target}</p><p className="muted"><b>신청</b> {p.apply}</p><a className="source" href={p.sourceUrl} target="_blank" rel="noreferrer">공식 출처 확인 →</a></article>)}</div><div className="notice">지원사업은 거주기간, 출생순위, 소득기준, 신청시점 등에 따라 달라질 수 있습니다. 신청 전 해당 지자체와 공식기관의 최신 공고를 확인하세요.</div></div></section>
  {region&&<section className="section localInfo"><div className="wrap infoSplit"><div className="infoPanel"><span className="insuranceBadge">{label} 지역 고유 정보</span><h2>{label}에서 함께 확인하세요</h2><p>{city?.note||region.summary}</p><ul className="checks"><li>지역 출산지원 사업과 지급조건</li><li>거주기간·출생순위·신청기한</li><li>산모·신생아 건강관리와 보건소 지원</li><li>다자녀·보육·가족센터 연계 지원</li></ul></div><div className="infoPanel infoPanelAccent"><span>📍</span><h3>{region.fullName}</h3><h2>{region.accent}</h2><p>지역명만 바꾼 페이지가 아니라 실제 지역의 지원정책과 생활권 정보를 확인해 페이지별 고유 콘텐츠로 확장합니다.</p></div></div></section>}
  <section className="section"><div className="wrap"><div className="ctaBox insuranceCta"><div><span className="darkEyebrow">올바른 보험</span><h2>{keyword}, 충분히 알아본 뒤 상담하세요</h2><p>가입시기와 보장내용, 지역별 출산지원 정보를 확인한 후 상담을 진행할 수 있습니다.</p></div><a className="btn ctaWhite" href={site.cpaUrl}>무료 상담 알아보기 →</a></div></div></section>
 </main>
}
