export type RegionalSupportItem={title:string;summary:string;benefit:string;eligibility:string;apply:string;sourceName:string;sourceUrl:string;verifiedAt:string};

const DATA:Record<string,RegionalSupportItem[]>={
서울태아보험:[{title:'서울형 산후조리경비',summary:'출산 후 산모 회복과 산후 건강관리를 위한 서울시 바우처입니다.',benefit:'첫째 100만원 · 둘째 120만원 · 셋째 이상 150만원',eligibility:'산모와 출생자녀의 서울 거주·출생신고 등 공식 세부요건 확인',apply:'출산일로부터 180일 이내, 탄생육아 몽땅정보통 또는 동주민센터',sourceName:'서울시 임신·출산 정보센터',sourceUrl:'https://seoul-agi.seoul.go.kr/postpartum-care',verifiedAt:'2026-09-03'},{title:'서울시 임산부 교통비',summary:'임신·출산 과정의 이동 부담을 줄이기 위한 교통비 바우처입니다.',benefit:'첫째 70만원 · 둘째 80만원 · 셋째 이상 100만원',eligibility:'신청일 기준 서울시 3개월 이상 계속 거주하는 임산부 등',apply:'임신 확인 후부터 출산 후 6개월 이내',sourceName:'탄생육아 몽땅정보통',sourceUrl:'https://umppa.seoul.go.kr/',verifiedAt:'2026-09-03'}],
부산태아보험:[{title:'부산광역시 출산지원금',summary:'첫만남이용권과 부산시 추가 지원을 함께 확인할 수 있는 출산지원 제도입니다.',benefit:'첫째 첫만남이용권 200만원 · 둘째 이후 300만원 + 부산시 추가 100만원',eligibility:'부산 출생아 대상, 거주·지급 세부요건 공식 안내 확인',apply:'행정복지센터·복지로·정부24',sourceName:'부산광역시 당신처럼 애지중지',sourceUrl:'https://www.busan.go.kr/childcare/childcare010101',verifiedAt:'2026-09-03'}],
인천태아보험:[{title:'인천 천사지원금',summary:'인천형 출생정책 i+ 1억드림의 양육지원입니다.',benefit:'연 120만원씩 7년 · 총 840만원',eligibility:'2023년 이후 출생아 중 인천 계속 거주 등 공식 요건 충족',apply:'정부24',sourceName:'인천광역시',sourceUrl:'https://www.incheon.go.kr/IC010205/view?repDt=2026-04-02&repSeq=DOM_0000000014462863',verifiedAt:'2026-09-03'},{title:'인천 임산부 교통비',summary:'임신·출산 이동 부담 완화를 위한 지원입니다.',benefit:'50만원',eligibility:'인천 6개월 이상 거주, 임신 12주~출산 후 90일 등',apply:'인천시 공식 정책안내 확인',sourceName:'인천광역시 복지혜택',sourceUrl:'https://www.incheon.go.kr/jobs/main/support/welfare/view.do?wl_srvc_sn=52',verifiedAt:'2026-09-03'}],
경기태아보험:[{title:'경기도 산후조리비',summary:'산모·신생아 건강보호와 출산가정 부담 완화 지원입니다.',benefit:'출생아 1명당 50만원',eligibility:'경기도 출산가정, 세부요건 시군 확인',apply:'관할 행정복지센터 등',sourceName:'경기도청',sourceUrl:'https://web1.gg.go.kr/contents/contents.do?ciIdx=987173&menuId=266159',verifiedAt:'2026-09-03'},{title:'경기도 산모·신생아 건강관리',summary:'건강관리사 방문을 통한 산후회복·신생아 양육 지원입니다.',benefit:'태아유형·출산순위·기간에 따라 차등',eligibility:'경기도 내 출산가정',apply:'출산예정일 40일 전~출산 후 30일, 보건소 또는 정부24',sourceName:'경기도청',sourceUrl:'https://web1.gg.go.kr/contents/contents.do?ciIdx=987174&menuId=266160',verifiedAt:'2026-09-03'}],
수원태아보험:[{title:'수원시 자녀출산·입양 지원금',summary:'출산순위별 차등 지원입니다.',benefit:'첫째 50만원 · 둘째 100만원 · 셋째 200만원 · 넷째 500만원 · 다섯째 이상 1,000만원',eligibility:'출산일 기준 신청인 수원시 180일 이상 연속 거주 등',apply:'관할 행정복지센터 최신 안내 확인',sourceName:'경기도청 시군별 출산장려금 현황',sourceUrl:'https://www.gg.go.kr/contents/contents.do?ciIdx=987110&menuId=266074',verifiedAt:'2026-09-03'}],
대전태아보험:[{title:'대전형 양육 기본수당',summary:'대전 영유아 가정의 양육 부담을 줄이는 지역지원입니다.',benefit:'매월 15만원 · 24~35개월 15만원 추가',eligibility:'0~2세 영유아, 보호자의 대전 6개월 이상 거주 등',apply:'주소지 행정복지센터',sourceName:'대전시 임신·출산 행복꾸러미',sourceUrl:'https://www.daejeon.go.kr/djbaby/contentsHtmlView.do?menuSeq=7398',verifiedAt:'2026-09-03'}],
울산태아보험:[{title:'울산 구·군 출산지원금',summary:'구·군과 출생순위에 따라 지원액이 달라집니다.',benefit:'중구 첫째 70·둘째+ 100만원 / 남·동·북구 첫째 60·둘째+ 100만원 / 울주 첫째 70·둘째 250·셋째+ 500만원',eligibility:'울산 출생등록 및 거주요건 등 구군별 기준 확인',apply:'거주지 행정복지센터',sourceName:'울산광역시 출산지원',sourceUrl:'https://www.ulsan.go.kr/u/welfare/contents.ulsan?mId=001003002000000000',verifiedAt:'2026-09-03'}],
대구태아보험:[{title:'대구 다자녀 고등학교 입학축하금',summary:'다자녀 가정의 교육비 부담을 줄이는 지원입니다.',benefit:'둘째 30만원 · 셋째 이상 50만원',eligibility:'2026년 대구 소재 고등학교 1학년 다자녀 가정 등 공고 요건',apply:'대구시 공식 공고의 접수방법 확인',sourceName:'대구광역시',sourceUrl:'https://www.daegu.go.kr/',verifiedAt:'2026-09-03'}],
광주태아보험:[{title:'임산부 직장맘 고용유지 지원',summary:'임산부의 출산휴가 사용과 고용유지를 돕는 사업장 지원입니다.',benefit:'요건 충족 중소사업장 사업주 부담금 100만원',eligibility:'광주시 공식 사업요건 충족 임산부 근로자 및 사업장',apply:'광주시 여성가족 관련 공식 안내 확인',sourceName:'광주광역시',sourceUrl:'https://www.gwangju.go.kr/woman/contentsView.do?pageId=woman26',verifiedAt:'2026-09-03'}],
세종태아보험:[{title:'세종시 출산축하금',summary:'세종시에 출생신고한 가정의 초기 양육비 부담을 지원합니다.',benefit:'출생아 1명당 120만원',eligibility:'세종시 출생신고·거주 등 세부요건 확인',apply:'읍면동 또는 행복출산 관련 공식 신청경로 확인',sourceName:'세종특별자치시',sourceUrl:'https://www.sejong.go.kr/',verifiedAt:'2026-09-03'}],
강원태아보험:[{title:'강원특별자치도 육아기본수당',summary:'도내 영유아 가정의 안정적인 양육을 지원하는 강원형 정책입니다.',benefit:'연령·출생연도별 지급기준에 따라 지원',eligibility:'아동 및 보호자의 도내 거주 등 해당 연도 기준 확인',apply:'주소지 읍면동 및 강원도 공식 안내 확인',sourceName:'강원특별자치도',sourceUrl:'https://state.gwd.go.kr/',verifiedAt:'2026-09-03'}],
충북태아보험:[{title:'충북 출산육아수당',summary:'충북 가치자람 플랫폼에서 출산·육아 가정의 수당 신청과 지원사업을 통합 안내합니다.',benefit:'출생연도·회차별 지급기준 적용',eligibility:'충북 거주 출산가정으로 출생일·거주기간 등 사업별 요건 확인',apply:'충북 가치자람 온라인 또는 행정복지센터. 온라인 사실확인 실패 시 방문 신청',sourceName:'충청북도 가치자람',sourceUrl:'https://gachi.chungbuk.go.kr/',verifiedAt:'2026-09-03'},{title:'출산 육아용품 무료 대여',summary:'2026년 운영 중인 출산·육아용품 대여 지원사업입니다.',benefit:'사업별 지정 육아용품 무료 대여',eligibility:'지역·품목별 이용대상 확인',apply:'가치자람 지원사업 안내에서 신청',sourceName:'충청북도 가치자람',sourceUrl:'https://gachi.chungbuk.go.kr/',verifiedAt:'2026-09-03'}],
충남태아보험:[{title:'35세 이상 임산부 의료비 지원',summary:'2026년 충남이 고령 임산부의 안전한 임신·출산을 위해 강화한 지원입니다.',benefit:'외래 진료·검사비 최대 50만원',eligibility:'35세 이상 충남 임산부, 세부 시행기준 확인',apply:'충남도 및 시군 보건소 최신 공고 확인',sourceName:'충청남도 2026 주요업무계획',sourceUrl:'https://www.chungnam.go.kr/',verifiedAt:'2026-09-03'},{title:'난임부부 시술비 지원 확대',summary:'난임가정의 치료 접근성을 높이기 위해 시술비 지원 제한을 완화합니다.',benefit:'2026 계획 기준 출산당 지원 횟수 제한 폐지 방향',eligibility:'난임 진단 등 세부 사업기준 확인',apply:'주소지 보건소 등 공식 안내 확인',sourceName:'충청남도 2026 주요업무계획',sourceUrl:'https://www.chungnam.go.kr/',verifiedAt:'2026-09-03'}],
전북태아보험:[{title:'전북 청년 1인 소상공인·농어업인 출산급여',summary:'고용보험 출산휴가 사각지대에 놓이기 쉬운 청년 1인 사업자·농어업인의 출산을 지원하는 2026 신설 정책입니다.',benefit:'본인 출산 90만원 · 배우자 출산 80만원',eligibility:'전북 청년 1인 소상공인·농어업인 등 세부 공고요건',apply:'전북도 인구청년정책과 및 시군 최신 공고 확인',sourceName:'전북특별자치도 2026 달라지는 제도와 시책',sourceUrl:'https://www.jeonbuk.go.kr/index.jeonbuk?menuCd=DOM_000000111009000000',verifiedAt:'2026-09-03'},{title:'출산여성농가도우미 지원 확대',summary:'출산 여성농업인의 영농 공백을 줄이기 위한 도우미 지원기간이 확대됐습니다.',benefit:'최대 100일 지원',eligibility:'출산 여성농업인 등 사업기준 충족',apply:'출산 전 30일 또는 출산 후 1년 내 이용 가능, 시군 확인',sourceName:'전북특별자치도 2026 달라지는 제도와 시책',sourceUrl:'https://www.jeonbuk.go.kr/index.jeonbuk?menuCd=DOM_000000111009000000',verifiedAt:'2026-09-03'}],
전남태아보험:[{title:'2026 전남 임신 사전건강관리',summary:'임신 준비 단계의 가임력 검사를 지원합니다.',benefit:'여성 최대 13만원 · 남성 최대 5만원',eligibility:'전남 공식 사업의 검사·신청 대상 기준 확인',apply:'보건소 등 공식 신청경로 확인',sourceName:'전라남도 2026 출산지원사업',sourceUrl:'https://www.jeonnam.go.kr/contentsView.do?menuId=jeonnam0504160100',verifiedAt:'2026-09-03'},{title:'신혼부부·다자녀가정 보금자리 지원',summary:'주거비 부담을 줄이기 위한 대출이자 지원입니다.',benefit:'대출이자 월 최대 25만원 · 3년',eligibility:'신혼부부·다자녀가정의 소득·주택 등 세부기준 확인',apply:'전남도·시군 공고 확인',sourceName:'전라남도 2026 출산지원사업',sourceUrl:'https://www.jeonnam.go.kr/contentsView.do?menuId=jeonnam0504160100',verifiedAt:'2026-09-03'}],
경북태아보험:[{title:'경북 산모·신생아 건강관리 지원',summary:'건강관리사 이용 바우처와 본인부담금 지원을 함께 운영합니다.',benefit:'바우처 5~40일, 45.6만원~1,860.4만원 범위 차등 · 본인부담금 최대 15일 구간별 90%',eligibility:'자녀수·태아유형·서비스 구간에 따라 차등',apply:'시군 보건소에서 신청시기·서비스유형 확인',sourceName:'경상북도 저출생 대응 주요시책',sourceUrl:'https://www.gb.go.kr/Main/support/page.do?mnu_uid=10519',verifiedAt:'2026-09-03'},{title:'경북 임산부 친환경 농산물 지원',summary:'임신·출산 가정에 친환경 농산물 꾸러미를 지원합니다.',benefit:'1인당 48만원 상당',eligibility:'2025년 1월 1일 이후 임신부 또는 출산 산모 등',apply:'경북도 및 시군 사업안내 확인',sourceName:'경상북도 저출생 대응 주요시책',sourceUrl:'https://www.gb.go.kr/Main/support/page.do?mnu_uid=10519',verifiedAt:'2026-09-03'}],
경남태아보험:[{title:'경남 출산가정 영양꾸러미 바우처',summary:'영아의 건강한 성장과 출산가정 부담 완화를 위해 도내 농축수임산물·가공식품 구매를 지원합니다.',benefit:'e경남몰 바우처 30만원(자부담 6만원 포함, 주거·의료급여 수급자 자부담 면제)',eligibility:'사업 시행 시군 거주, 2025년 7월~2026년 6월 출생 영아 등 시군별 모집기준 확인',apply:'경남바로서비스 온라인 또는 보건소 방문, 시군별 접수기간 상이',sourceName:'경남바로서비스',sourceUrl:'https://baro.gyeongnam.go.kr/baro/',verifiedAt:'2026-09-03'}],
제주태아보험:[{title:'제주 해피아이 육아지원금',summary:'첫째와 둘째 이상 자녀의 장기 양육비를 출생순위별로 지원합니다.',benefit:'첫째 총 500만원(5년 분할) · 둘째 이상 총 1,000만원(9년 분할)',eligibility:'출생일 전 첫째 6개월·둘째 이상 12개월 이전부터 부모 중 1명이 제주에 계속 주소를 두는 등 요건',apply:'주소지 읍면동 또는 정부24 행복출산',sourceName:'제주인구정책 통합플랫폼',sourceUrl:'https://jeju.go.kr/lifecycle/policy/list.htm?act=view&page=4&seq=49',verifiedAt:'2026-09-03'}]
};

export function getRegionalSupport(regionSlug?:string,citySlug?:string){if(citySlug&&DATA[citySlug])return DATA[citySlug];if(regionSlug&&DATA[regionSlug])return DATA[regionSlug];return [];}
